version: "3.6"



services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
     
    volumes:
      - ${basePath}/hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # container_name: datanode
    restart: always
    volumes:
      - ${basePath}/hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  
  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    # container_name: datanode
    restart: always
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
  nifi:
    image: apache/nifi
    container_name: nifi
    restart: unless-stopped
    ports:
      # HTTP
      - 8080:8080/tcp
      # HTTPS
      - 8443:8443/tcp
      # Remote Input Socket
      - 10000:10000/tcp
      # JVM Debugger
      - 8000:8000/tcp
      # Cluster Node Protocol
      #- 11443:11443/tcp
    volumes:
      # mkdir /var/lib/nifi && chown -R 1000:1000 /var/lib/nifi
      - ${basePath}/nifi/database_repository:/opt/nifi/nifi-current/database_repository
      - ${basePath}/nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository
      - ${basePath}/nifi/content_repository:/opt/nifi/nifi-current/content_repository
      - ${basePath}/nifi/provenance_repository:/opt/nifi/nifi-current/provenance_repository
      - ${basePath}/nifi/state:/opt/nifi/nifi-current/state
      - ${basePath}/nifi/logs:/opt/nifi/nifi-current/logs
# volumes:
#   hadoop_namenode:
#     driver_opts:
#       type: "nfs"
#       device: ${basePath}/hadoop_namenode
#   hadoop_datanode:
#     driver_opts:
#       type: "nfs"
#       device: ${basePath}/hadoop_datanode
  # shared-workspace:
  #   name: "hadoop-distributed-file-system"
  #   driver: local